min_version = { hard = '2026.1.0', soft = '2026.5.0' }
[tools]
node = { version = "24", postinstall = "corepack enable" }
"npm:@salesforce/cli" = { version = "2", trust_policy_excludes = ["pino@9.14.0","fastq@1.20.2"] }

[settings]
experimental = true
minimum_release_age = "3d"
lockfile = true
auto_install = true

[env]
_.path = ["{{config_root}}/node_modules/.bin"]