name: "Authenticate org"
description: "Authenticate a Salesforce org"
inputs:
  auth-URL:
    description: "The auth URL for use with sfdx auth:sfdxurl:store"
    required: true
  alias:
    description: "Alias for the authenticated org"
    required: true
  setDefaultUsername:
    description: Set the authenticated org as the default username that all commands run against.
    required: true
  setDefaultDevhubUsername:
    description: Set the authenticated org as the default dev hub org for scratch org creation
    required: true
runs:
  using: "composite"
  steps:
    # Authenticate org
    - name: Authenticate org
      run: |
        defaultValues = ""
        if [ ${{ github.event.inputs.setDefaultUsername }} == true ]; then
          defaultValues += " -d"
        fi

        if [ ${{ github.event.inputs.setDefaultDevhubUsername }} == true ]; then
          defaultValues += " -s"
        fi

        echo ${{ github.event.inputs.auth-URL }} > ./SFDX_URL.txt
          sfdx auth:sfdxurl:store --sfdxurlfile ./SFDX_URL.txt -a ${{ github.event.inputs.alias }}$(defaultValues)
        rm -f ./SFDX_URL.txt
      shell: bash