name: "Authenticate org"
description: "Authenticate a Salesforce org"
inputs:
  auth-url:
    description: "The auth URL for use with sf org login"
    required: true
  alias:
    description: "Alias for the authenticated org"
    required: true
  setDefaultUsername:
    description: "Set the authenticated org as the default username that all commands run against."
    default: "false"
    required: false
  setDefaultDevhubUsername:
    description: "Set the authenticated org as the default dev hub org for scratch org creation"
    default: "false"
    required: false
runs:
  using: "composite"
  steps:
    # Authenticate org
    - name: Authenticate org
      run: |
        printf -v red '\033[0;31m'
        printf -v yellow '\033[0;33m'
        printf -v green '\033[0;32m'
        printf -v bold '\033[1m'
        printf -v reset '\033[0m'

        echo "${yellow}${bold}------------------------------------------------------------------------------------------${reset}"
        echo "${yellow}${bold}Authenticate org 🔒${reset}"
        echo "${yellow}${bold}------------------------------------------------------------------------------------------${reset}"

        command=(sf org login sfdx-url --sfdx-url-stdin --json --alias ${ALIAS})

        if [ "${SET_DEFAULT_USERNAME}" == "true" ]; then
            command+=(--set-default)
        fi

        if [ "${SET_DEFAULT_DEVHUB_USERNAME}" == "true" ]; then
            command+=(--set-default-dev-hub)
        fi

        echo "${AUTH_URL}" | "${command[@]}" > loginResult.json

        if [ "$(jq .status loginResult.json)" -eq 1 ]; then
            echo "::error title=Failed to authenticate::$(jq .message loginResult.json)"
            rm -f ./loginResult.json
            exit 1
        else
            echo "${green}${bold}Authenticate org successful.${reset}"
        fi

        echo "${yellow}${bold}------------------------------------------------------------------------------------------${reset}"

        rm -f ./loginResult.json
      shell: bash
      env:
        AUTH_URL: ${{ inputs.auth-url }}
        ALIAS: ${{ inputs.alias }}
        SET_DEFAULT_USERNAME: ${{ inputs.setDefaultUsername }}
        SET_DEFAULT_DEVHUB_USERNAME: ${{ inputs.setDefaultDevhubUsername }}
