name: "Authenticate org"
description: "Authenticate a Salesforce org"
inputs:
  auth-URL:
    description: "The auth URL for use with sfdx auth:sfdxurl:store"
    required: true
  alias:
    description: "Alias for the authenticated org"
    required: true
  setDefaultUsername:
    description: Set the authenticated org as the default username that all commands run against.
    required: true
  setDefaultDevhubUsername:
    description: Set the authenticated org as the default dev hub org for scratch org creation
    required: true
runs:
  using: "composite"
  steps:
    # Authenticate org
    - name: Authenticate org
      run: |
        echo ${{ inputs.auth-URL }} > ./SFDX_URL.txt
        
        if [ ${{ inputs.setDefaultUsername }} && ${{ inputs.setDefaultDevhubUsername }} ]; then
          sfdx auth:sfdxurl:store --sfdxurlfile ./SFDX_URL.txt -a ${{ inputs.alias }} --setdefaultdevhubusername --setdefaultusername
        elif [ ${{ inputs.setDefaultUsername }} ]; then
          sfdx auth:sfdxurl:store --sfdxurlfile ./SFDX_URL.txt -a ${{ inputs.alias }} --setdefaultusername
        elif [ ${{ inputs.setDefaultDevhubUsername }} ]; then
          sfdx auth:sfdxurl:store --sfdxurlfile ./SFDX_URL.txt -a ${{ inputs.alias }} --setdefaultdevhubusername
        else
          sfdx auth:sfdxurl:store --sfdxurlfile ./SFDX_URL.txt -a ${{ inputs.alias }}
        fi
        rm -f ./SFDX_URL.txt
      shell: bash