name: "Package version updater"
description: "Update the minor version of sfdx-project.json"
runs:
  using: "composite"
  steps:
    - name: Update version number
      run: |
        newVersion=$(jq -r '.packageDirectories[0].versionNumber' sfdx-project.json |
          awk -F. -v OFS=. '{$2++ ; print}')
        file=$(mktemp)
        jq --indent 4 -r ".packageDirectories[0].versionNumber = \"$newVersion\"" sfdx-project.json > "$file"
        cat "$file" > sfdx-project.json
        rm "$file"
      shell: bash