name: "Install SF"
description: "Install SF cli with npm"
inputs:
  version:
    description: "Version for the SF CLI version"
    default: "2.5.8"
    required: false
runs:
  using: "composite"
  steps:
    # Install SF CLI
    - name: Install SF CLI|
      run: |
        npm install --global @salesforce/cli@${{ inputs.sfVersion }}
        echo sf version: $(sf --version)
        SFDX_DISABLE_DNS_CHECK=true
      shell: bash
