name: "Install SFDX"
description: "Install SFDX cli with npm"
inputs:
  version:
    description: "Version for the SFDX CLI version"
    default: "7.202.7"
    required: false
runs:
  using: "composite"
  steps:
    # Install SFDX
    - name: Install SFDX
      run: |
        npm install --global sfdx-cli@${{ inputs.version }}
        npm install --global @salesforce/cli@${{ inputs.version }}
        sfdx --version | tee output
        echo SFDX version $output
        SFDX_DISABLE_DNS_CHECK=true
      shell: bash