name: Fill Scratch Pools
description: Action to fill scratch org pools
inputs:
  dev-hub:
    description: The alias of the Dev Hub org
    required: true
  sfdx-project-path:
    description: The path to sfdx-project.json
    required: false
  package-key:
    description: The key of the packages to install
    required: false
  pool-config-path:
    description: The path to the pool configuration file
    required: true
  is-ci-pool:
    description: Whether this is a CI pool
    required: false
    default: "false"
  pool-tag:
    description: The tag of the pool to manage
    required: true

runs:
  using: "composite"
  steps:
    - name: Check Dev Hub scratch limits
      shell: bash
      env:
        DEV_HUB: ${{ inputs.dev-hub }}
      run: bash "$GITHUB_ACTION_PATH/scripts/check_scratch_limits.sh"

    - name: Prepare pool
      shell: bash
      env:
        CRM_PACKAGE_KEY: ${{ inputs.package-key }}
        SFDX_PROJECT_PATH: ${{ inputs.sfdx-project-path }}
        POOL_CONFIG_PATH: ${{ inputs.pool-config-path }}
        DEV_HUB: ${{ inputs.dev-hub }}
      run: bash "$GITHUB_ACTION_PATH/scripts/prepare_pool.sh"

    - name: Delete orphans
      uses: navikt/sf-gha-deleteScratchPool@1f0986d2312a2969e658946acb496f6dcd7d4032
      with:
        devhub: ${{ inputs.dev-hub }}
        deleteJobType: orphans
        isCiPool: ${{ inputs.is-ci-pool }}
        poolTag: ${{ inputs.pool-tag }}
