name: Generate package key pairs
description: Generate package key pairs based on submitted package key and path to sfdx-project.json
inputs:
  sfdx-project-path:
    description: Path to sfdx-project.json
    required: true
  package-key:
    description: Installation key to apply to password-protected dependencies
    required: true
  devhub-alias:
    description: Alias of the Dev Hub org to use for retrieving package version information
    required: false
    default: devhub
outputs:
  package-keys:
    description: Space-separated list of package:key pairs for protected dependencies
    value: ${{ steps.create_keys.outputs.package-keys }}
runs:
  using: composite
  steps:
    - name: Create package key pairs
      id: create_keys
      shell: bash
      env:
        CRM_PACKAGE_KEY: ${{ inputs.package-key }}
        SFDX_PROJECT_PATH: ${{ inputs.sfdx-project-path }}
        DEVHUB_ALIAS: ${{ inputs.devhub-alias }}
      run: |
        set -euo pipefail
        echo "::add-mask::${CRM_PACKAGE_KEY}"
        keys="$(
          bash "$GITHUB_ACTION_PATH/scripts/createPackageKeyPairs.sh" \
            --sfdx-project-path "$SFDX_PROJECT_PATH" \
            --package-key "$CRM_PACKAGE_KEY" \
            --devhub "$DEVHUB_ALIAS" \
            --latest-fallback
        )"
        echo "package-keys=${keys}" >> "$GITHUB_OUTPUT"
