name: 'CD - Deploy'

on:
  workflow_call:
    secrets:
      CRM_PROD_SFDX_URL:
        required: true
      AUTH_URL:
        required: true


jobs:
  deploy:
    name: 'Deploy'
    runs-on: ubuntu-latest
    container: ghcr.io/flxbl-io/sfops
    permissions:
      contents: read
      packages: read
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4

      - name: 'Download Artifacts'
        uses: actions/download-artifact@v4
        with:
          name: quickbuild-artifacts
          path: artifacts 

      - name:  'Authenticate Dev Hub'
        uses: navikt/crm-workflows-base/.github/actions/authenticateOrg@dxAtScale
        with:
          auth-url: ${{ secrets.CRM_PROD_SFDX_URL }}
          alias: devhub
          
      - name:  'Authenticate Sandbox'
        uses: navikt/crm-workflows-base/.github/actions/authenticateOrg@dxAtScale
        with:
          auth-url: ${{ secrets.AUTH_URL }}
          alias: dev

      - name: 'Deploy to DEV'
        run: |
          sfp dependency install --targetusername dev --targetdevhubusername devhub
          sfp install --targetorg dev  --skipifalreadyinstalled --logsgroupsymbol "::group::,::endgroup::" 
