name: 'CD - Generate Release Definition File'

on:
  workflow_call:
    inputs:
      branchToCommitTo:
        description: "Repository branch in which the release definition files are to be written"
        required: false
        default: "master"
        type: string
      gitRef:
        description: "Utilize the tags on the source branch to generate release definiton"
        required: true
        type: string
      pathToConfigFile:
        description: "Path to release config file"
        required: true
        type: string
      releaseName:
        description: "Name of the release"
        required: true
        type: string
      directory:
        description: "Relative path to directory to which the release defintion file should be generated"
        required: false
        default: "./release-definitions"
        type: string
    
jobs:
  generateReleaseDefinition:
    runs-on: ubuntu-latest
    container: ghcr.io/flxbl-io/sfops
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Generate release definition file
      - name: Generate release definition file
        run: |
          sfp releasedefinition generate --gitref ${{ inputs.gitRef }} --configfile ${{ inputs.pathToConfigFile }} --releasename ${{ inputs.releaseName }} --directory ${{ inputs.directory }} --branchname ${{ inputs.branchToCommitTo }}