name: 'Create Scratch Pool'

on:
  workflow_dispatch:

jobs:
  pool:
    name: 'Replenish Dev Pool'
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.gitRef }}
          fetch-depth: 0