name: 'Replenish DEV Pools - Auto Triggered'

on:
  workflow_dispatch:
    inputs:
      gitRef:
        description: "Commit Id from where the pools should be created"
        required: false
        default: 'main'

jobs:
  pool:
    name: 'Replenish Dev Pool'
    runs-on: ubuntu-latest
    container: ghcr.io/dxatscale/sfpowerscripts
    timeout-minutes: 720 #Set to Maximum Time out
    steps:

      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.gitRef }}
          fetch-depth: 0


      - name:  'Authenticate Dev Hub'
        uses: navikt/crm-workflows-base/.github/actions/authenticateOrg@dxAtScale
        with:
          auth-url: ${{ secrets.CRM_PROD_SFDX_URL }}
          alias: devhub

      # Authenticate to npm
      - uses: actions/setup-node@v4
        with:
          registry-url: 'https://npm.pkg.github.com'

      - name: 'Prepare a pool of scratch orgs'
        run: |
          export SFPOWERSCRIPTS_ARTIFACT_PACKAGE=04t7U000000Y2XzQAK
          'sfp orchestrator:prepare --poolconfig config/project-dev-pool-def.json --targetdevhubusername devhub'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}