# DX@Scale CI/CD Template for GitHub
#----------------------------------------------------------------------------------------------------
# Follows reference pipeline available at docs.dxatscale.io
# 
#-----------------------------------------------------------------------------------------------------
# To know more about dxatscale, visit https://docs.dxatscale.io
# To know more on sfpowerscripts, visit- https://docs.dxatscale.io/sfpowerscripts/sfpowerscripts


# This pipeline quickbuilds, deploy to DEV, builds and publishes packages to artifact repository

name: 'CI Pipeline - Auto Triggered'


on:
  workflow_call:
    secrets:
      CRM_PROD_SFDX_URL:
        required: true
      CRM_SIT_SFDX_URL:
        required: true
  workflow_dispatch:



#Set the environment variables for tracking metrics
#env:
  #SFPOWERSCRIPTS_NEWRELIC: 'true'
  #SFPOWERSCRIPTS_NEWRELIC_API_KEY: '${{ secrets.NEWRELIC_INSIGHT_INSERT_KEYS }}'
  #SFPOWERSCRIPTS_DATADOG: 'true'
  #SFPOWERSCRIPTS_DATADOG_HOST: '${{ secrets.DATADOG_HOST }}'
  #SFPOWERSCRIPTS_DATADOG_API_KEY: '${{ secrets.DATADOG_API_KEY }}'


jobs:
  validate:
    name: 'Validate'
    uses: navikt/crm-workflows-base/.github/workflows/ciValidate.yml@dxAtScale
    permissions:
      contents: read
      packages: write
    secrets: inherit
    if: github.ref == 'refs/heads/master'

  quickbuild:
    name: 'Quickbuild'
    needs: validate
    uses: navikt/crm-workflows-base/.github/workflows/ciQuickBuild.yml@dxAtScale
    permissions:
      contents: read
      packages: write
    secrets: inherit
    if: github.ref == 'refs/heads/master'

  deploy:
    name: 'Deploy'
    uses: navikt/crm-workflows-base/.github/workflows/cdDeploy.yml@dxAtScale
    needs: quickbuild
    permissions:
      contents: read
      packages: read
    secrets:
      CRM_PROD_SFDX_URL: ${{ secrets.CRM_PROD_SFDX_URL }}
      AUTH_URL: ${{ secrets.CRM_SIT_SFDX_URL }}


  buildPromotePublish:
    name: 'Build and Publish'
    runs-on: ubuntu-latest
    container: ghcr.io/flxbl-io/sfops
    permissions:
      contents: write
      packages: write
    needs: deploy
    concurrency: build 
    if: github.ref == 'refs/heads/master'
    steps:
      - name:  'Checkout'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name:  'Authenticate Dev Hub'
        uses: navikt/crm-workflows-base/.github/actions/authenticateOrg@dxAtScale
        with:
          auth-url: ${{ secrets.CRM_PROD_SFDX_URL }}
          alias: devhub

      - name: 'Create packages'
        id: sfpowerscripts-build
        run: |
          sfp build --devhubalias devhub --diffcheck --branch ${GITHUB_REF#refs/heads/} --buildnumber ${GITHUB_RUN_ID}

      # - name: 'Promote package'
      #   id: sfpowerscripts-promote
      #   run: |
      #     sfp artifacts promote --targetdevhubusername devhub --artifactdir artifacts

      - name: 'Publish artifacts'
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: artifacts

      - name: 'Authenticate to npm'
        uses: actions/setup-node@v4
        with:
          registry-url: 'https://npm.pkg.github.com'

      - name: 'Publish'
        run: |
          sfp publish --artifactdir artifacts --npm --scope @${{ github.repository_owner }}  --gittag --pushgittag
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}