name: 'CD - Quick build packages'

on:
  workflow_call:
    secrets:
      CRM_PROD_SFDX_URL:
        required: true

jobs:
  quickbuild:
    name: 'Quickbuild packages'
    runs-on: ubuntu-latest
    container: ghcr.io/flxbl-io/sfops
    permissions:
      contents: read
      packages: write 
    steps:
      - uses: actions/checkout@v4

      - uses: navikt/crm-workflows-base/.github/actions/authenticateOrg@dxAtScale
        with:
          auth-url: ${{ secrets.CRM_PROD_SFDX_URL }}
          alias: devhub

      - name: 'Create packages'
        id: sfpowerscripts-build
        run: |
          sfp quickbuild --devhubalias devhub --diffcheck --buildnumber ${GITHUB_RUN_ID} --branch ${GITHUB_REF#refs/heads/}
            
      # Publish artifacts
      - uses: actions/upload-artifact@v4
        with:
          name: quickbuild-artifacts
          path: artifacts