on:
  workflow_call:
    inputs:
      pools:
        required: false
        type: string
        description: "Fetch scratch-org validation environment from one of listed pools, sequentially"
        default: "ci"
      coveragepercent:
        required: false
        type: number
        description: "Minimum required percentage coverage for validating code coverage of packages with Apex classes"
        default: 85
jobs:
  validate:
    name: Validate Build
    runs-on: ubuntu-latest
    container: ghcr.io/flxbl-io/sfops
    defaults:
      run:
        shell: "bash"
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.gitRef }}
          fetch-depth: "0"
      - uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'
      - name: "Set Git Config"
        run: |
          git config --global user.email "<>"
          git config --global user.name "GitHub Action"
          git config --system --add safe.directory $GITHUB_WORKSPACE

      - name: "Authenticate Dev Hub"
        uses: navikt/crm-workflows-base/.github/actions/authenticateOrg@dxAtScale
        with:
          auth-url: ${{ secrets.CRM_PROD_SFDX_URL }}
          alias: devhub

      - name: "Install dev dependencies"
        run: |
          npm install

      - name: "Verify prettier"
        run: |
          #Find diff
          mapfile -t diffed_files_to_lint < <(git diff --name-only --diff-filter=d HEAD~ -- \*.{cls,cmp,component,css,html,js,json,md,page,trigger,xml,yaml,yml})
          npx prettier "${diffed_files_to_lint[@]}" --check

      - name: "Run eslint"
        run: |
          mapfile -t diffed_files_to_lint < <(git diff --diff-filter=d --name-only HEAD~ -- \*.js)
          npx eslint --no-error-on-unmatched-pattern "${diffed_files_to_lint[@]}"

      - name: "Get diff sf file names"
        id: getDiff
        run: |
          #mapfile -t diffedSfFiles < <(git diff --name-only --diff-filter=d HEAD~ -- \*.{cls,cmp,component,css,html,js,json,page,trigger,xml})
          shopt -s globstar
          diffedSfFiles=(**/*.xml) # temporary hack to always run the next step
          json=$(jq -c -n '$ARGS.positional' --args "${diffedSfFiles[@]}")
          echo "diffedSfFiles=$json" >> $GITHUB_OUTPUT

      - name: Run Salesforce Code Analyzer
        id: run-code-analyzer
        uses: forcedotcom/run-code-analyzer@v1
        if: steps.getDiff.outputs.diffedSfFiles != '[]'
        with:
          run-command: run
          run-arguments: --normalize-severity --target fromJson(${{ steps.getDiff.outputs.diffedSfFiles }}) --outfile results.html
          results-artifact-name: salesforce-code-analyzer-results

      - name: Check the Salesforce Code Analyzer outputs to determine whether to fail
        if: |
          steps.run-code-analyzer.outputs.exit-code > 0 ||
          steps.run-code-analyzer.outputs.num-sev1-violations > 0 ||
          steps.run-code-analyzer.outputs.num-violations > 10
        run: exit 1
