on:
  workflow_call:
    inputs:
      pools:
        required: false
        type: string
        description: 'Fetch scratch-org validation environment from one of listed pools, sequentially'
        default: 'ci'
      coveragepercent:
        required: false
        type: number
        description:  'Minimum required percentage coverage for validating code coverage of packages with Apex classes'
        default: 85
jobs:
  validate:
    name: Validate Pool
    runs-on: ubuntu-latest
    container: ghcr.io/flxbl-io/sfops
    defaults:
      run:
        shell: 'bash'
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.gitRef }}
          fetch-depth: '0'
      - run: echo $(ls -a)
      - name: 'Set Git Config'
        run: |
          git config --global user.email "<>"
          git config --global user.name "GitHub Action"
          git config --system --add safe.directory $GITHUB_WORKSPACE
          echo "GITHUB_WORKSPACE $GITHUB_WORKSPACE"
          echo "GIT_DIR $GIT_DIR"
          echo "pwd $(pwd)"

      - name:  'Authenticate Dev Hub'
        uses: navikt/crm-workflows-base/.github/actions/authenticateOrg@dxAtScale
        with:
          auth-url: ${{ secrets.CRM_PROD_SFDX_URL }}
          alias: devhub

      - name:  'Authenticate Npm'
        uses: actions/setup-node@v4
        with:
          registry-url: 'https://npm.pkg.github.com'
          cache: "npm"

      # - name: 'Install dev dependencies'
      #   run: |
      #     echo $(ls -a)
      #     npm install -D

      - name: 'Verify prettier'
        run: |
          echo $(ls -a)
          git --version
          echo $GITHUB_WORKSPACE
          echo $GIT_DIR
          echo $(pwd)
          echo $(ls .git/refs/heads)
          echo "status $(git status)"
          #Find diff
          DIFFED_FILES_TO_LINT=$(git diff --name-only origin/HEAD~ -- *.{cls,cmp,component,css,html,js,json,md,page,trigger,xml,yaml,yml})
          npx prettier $DIFFED_FILES_TO_LINT --check

          # Start the language server for improved parsing performance,
          # and put it in the background (*nix only) so that next commands can be run.
          nohup start-apex-server >/dev/null 2>&1 &
          # Wait until the server is up before sending requests
          npx wait-on http://localhost:2117/api/ast/
          # Check that Apex files are formatted according to Prettier Apex style
          prettier --plugin=prettier-plugin-apex --apex-standalone-parser built-in --check $DIFFED_FILES_TO_LINT 
          # Clean up the language server
          stop-apex-server

      - name: 'Validate'
        run: |
          # Create package key string for use in validate
          keys=""
          packageNames=$(jq --raw-output '.packageAliases | keys | join(" ")' sfdx-project.json)
          for p in $packageNames; do
            keys+="$p:${{secrets.CRM_PACKAGE_KEY}} "
          done

          # Run validate using scratch org from pools
          sfp validate --pools "${{ inputs.pools }}" --targetdevhubusername devhub --coveragepercent ${{ inputs.coveragepercent }} --keys "$keys" --deletescratchorg