name: Deploy package
on:
  workflow_call:
    inputs:
      packageId:
        description: "Package ID"
        required: true
        type: string
      org:
        description: "Org (prod, preprod, dev, uat, sit)"
        required: true
        type: string
      unpackagable:
        description: "Path to unpackageable folder"
        required: false
        type: string
    outputs:
      successfullyInstalledPackage: ${{ jobs.deploy-package.outputs.successfullyInstalled }}
      installPackageOutput: ${{ jobs.deploy-package.outputs.installOutput }}
      installMetadata: ${{ jobs.deploy-package.outputs.installMetadata }}
      successfullyDeployedMetadata: ${{ jobs.deploy-package.outputs.successfullyDeployedMetadata }}
      deployMetadataOutput: ${{ jobs.deploy-package.outputs.deployOutput }}
jobs:
  deploy-package:
    name: Deploy Package
    runs-on: ubuntu-latest
    steps:
      # Set SFDX Auth URL
      - name: Set SFDX Auth URL
        id: auth-url
        run: |
          if [ ${{ inputs.org }} == "prod" ];then
            echo "target=$(echo ${{ secrets.CRM_PROD_SFDX_URL }})" >> $GITHUB_ENV
            echo "'prod' was set"
          elif [ ${{ inputs.org }} == "preprod" ];then
            echo "target=$(echo ${{ secrets.CRM_PREPROD_SFDX_URL }})" >> $GITHUB_ENV
            echo "'preprod' was set"
          elif [ ${{ inputs.org }} == "dev" ];then
            echo "target=$(echo ${{ secrets.DEV_SFDX_URL }})" >> $GITHUB_ENV
            echo "'dev' was set"
          elif [ ${{ inputs.org }} == "uat" ];then
            echo "target=$(echo ${{ secrets.CRM_UAT_SFDX_URL }})" >> $GITHUB_ENV
            echo "'uat' was set"
          elif [ ${{ inputs.org }} == "sit" ];then
            echo "target=$(echo ${{ secrets.CRM_SIT_SFDX_URL }})" >> $GITHUB_ENV
            echo "'sit' was set"
          else
            echo "target=$(echo ${{ github.event.inputs.org }})" >> $GITHUB_ENV
            echo "input org was set to input"
          fi

      # Install SFDX
      - name: Install SFDX
        uses: navikt/crm-workflows-base/.github/actions/installSFDX@master

      # Authorize SFDX
      - name: Authorize SFDX
        uses: navikt/crm-workflows-base/.github/actions/authenticateOrg@master
        with:
          auth-url: ${{ env.target }}
          alias: targetOrg
          setDefaultUsername: true
          setDefaultDevhubUsername: false

      # Install package in target org
      - name: Install package in target org
        id: installPackage
        run: |
          sfdx force:package:install --package ${{ inputs.packageId }} --installationkey ${{ secrets.CRM_PACKAGE_KEY }} --wait 10 --publishwait 10 --noprompt | tee output
          echo "installOutput=$(cat output | jq '.message')" >> $GITHUB_OUTPUT
          if [ $(cat output | jq '.status') == "0" ]; then
            echo "successfullyInstalled=true" >> $GITHUB_OUTPUT
          else
            echo "successfullyInstalled=false" >> $GITHUB_OUTPUT
          fi

      # Checkout source code
      - name: Checkout source code from master
        uses: actions/checkout@v3

      # Deploy unpackagable content
      - name: Deploy unpackagable content
        id: deployMetadata
        run: |
          if [ -d "${{ inputs.unpackagable }}" ]; then
            echo "Starting deployment of ${{ inputs.unpackagable }}"
            echo "installMetadata=true" >> $GITHUB_OUTPUT
            sfdx force:source:deploy --sourcepath ${{ inputs.unpackagable }} --testlevel RunLocalTests | tee output
            echo "deployOutput=$(cat output | jq '.message')" >> $GITHUB_OUTPUT
            if [ $(cat output | jq '.status') == "0" ]; then
              echo "successfullyDeployedMetadata=true" >> $GITHUB_OUTPUT
            else
              echo "successfullyDeployedMetadata=false" >> $GITHUB_OUTPUT
            fi
          else
            echo "installMetadata=false" >> $GITHUB_OUTPUT
          fi

    outputs:
      successfullyInstalledPackage: ${{ steps.installPackage.outputs.successfullyInstalled }}
      installPackageOutput: ${{ steps.installPackage.outputs.installOutput }}
      installMetadata: ${{ steps.deployMetadata.outputs.installMetadata }}
      successfullyDeployedMetadata: ${{ steps.deployMetadata.outputs.successfullyDeployedMetadata }}
      deployMetadataOutput: ${{ steps.deployMetadata.outputs.deployOutput }}
