name: Publsh community
on:
  workflow_call:
    inputs:
      org:
        description: "Org (prod, preprod, dev, uat, sit)"
        required: true
        type: string
      community-name:
        description: "Name of the experience site to publish"
        required: true
        type: string
permissions: {}
concurrency:
  group: "${{ github.workflow }}-${{ inputs.org }}-${{ inputs.community-name }}"
  cancel-in-progress: false
jobs:
  deploy-package:
    name: Publish community
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      # Install SF
      - name: Install SF
        uses: navikt/sf-gha-install-sf-cli@3f1abbc990b03fb544e80169920fea2e94946d1a

      # Authorize SF
      - name: Authorize SF
        uses: navikt/sf-gha-authenticateOrg@da2f995ee865e05111574719abfc5ba12b459f0c
        with:
          auth-url: ${{ inputs.org == 'prod' && secrets.PROD_AUTH_URL || inputs.org == 'preprod' && secrets.PREPROD_AUTH_URL || inputs.org == 'dev' && secrets.DEV_AUTH_URL || inputs.org == 'uat' && secrets.UAT_AUTH_URL || secrets.SIT_AUTH_URL }}
          alias: targetOrg
          setDefaultUsername: true
          setDefaultDevhubUsername: false

      - name: Publish
        run: |
          sf community publish --name "$COMMUNITY_NAME" --target-org targetOrg --json
        env:
          COMMUNITY_NAME: ${{ inputs.community-name }}
