name: "Validate With Salesforce Code Analyzer"
on:
  workflow_call:
jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:

      # Checkout source code
      - name: Checkout source code
        uses: actions/checkout@v3

        # Delete scratch-org folder
      - name: Delete scratch-org folder
        run: |
          rm -rf ./force-app/scratch-org

      # Install SF
      - name: Install SF
        uses: navikt/crm-workflows-base/.github/actions/installSF@master

      # Install Salesforce Code Analyzer
      - name: Install Salesforce Code Analyzer
        uses: navikt/crm-workflows-base/.github/actions/installSalesforceCodeAnalyzer@master

      - name: Run copy pasta detection
        run: |
          sf scanner run --target ./force-app --engine cpd --normalize-severity --verbose --json | tee output
          echo "$(jq --raw-output --arg pwd "$PWD" '.result[] | "\(.fileName | split($pwd)[1]) has \( .violations | length ) violation(s)"' <<< "$output")"
          echo
          echo "WARNINGS"
          echo "$(jq '.warnings[]' <<< "$output")"

      - name: Run Code Analyzer
        run: |
          sf scanner run --target ./force-app --normalize-severity --format json --outfile scannerResult.json | tee output
          echo "$(jq --raw-output --arg pwd "$PWD" '.result[] | "\(.fileName | split($pwd)[1]) has \( .violations | length ) violation(s)"' <<< "$output")"
          echo
          echo "WARNINGS"
          echo "$(jq --raw-output '.warnings[]' <<< "$output")"

      - name: Run Data Flow Analysis
        run: |
          sf scanner run:dfa --projectdir ./force-app --target ./force-app --normalize-severity --format json --outfile scannerResult.json | tee output
          echo "$(jq --raw-output --arg pwd "$PWD" '.result[] | "\(.fileName | split($pwd)[1]) has \( .violations | length ) violation(s)"' <<< "$output")"
          echo
          echo "WARNINGS"
          echo "$(jq --raw-output '.warnings[]' <<< "$output")"